describe('Login', () => {
    const login = (username) => {
        cy.session(username, () => {
            cy.visit('https://automationexercise.com/login')
            cy.get('[data-qa="login-email"]').type(username)
            cy.get('[data-qa="login-password"]')
                .type("@Demo1234@!@")
            cy.get('[data-qa="login-button"]')
                .click()
        })
    }
    beforeEach(() => {
        login("omed1@gmail.com")
    })
    it('Login', () => {
        cy.visit('https://automationexercise.com/')
        cy.get('.shop-menu > .nav > :nth-child(2) > a')
            .should('be.visible')
            .and('contain.text', 'Products')
            .click()
        cy.url().should('eq', 'https://automationexercise.com/products')
        cy.get('h2.title.text-center')
            .should('have.text', 'All Products')
        cy.get('.product-image-wrapper')
            .should('have.length', 34)
        cy.get(':nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn')
            .should('be.visible')
            .and('have.text', 'Add to cart')
            .click()
        cy.get('u')
            .should('have.text', 'View Cart')
            .click()
        cy.url().should('eq', 'https://automationexercise.com/view_cart')
        cy.get('.col-sm-6 > .btn')
            .should('be.visible')
            .and('have.text', 'Proceed To Checkout')
            .click()
        cy.get(':nth-child(7) > .btn')
            .should('be.visible')
            .and('have.text', 'Place Order')
            .click()
        cy.get('[data-qa="name-on-card"]')
            .should('be.visible')
            .type('demouser')
        cy.get('[data-qa="card-number"]')
            .should('be.visible')
            .type('4242424242424242')
        cy.get('[data-qa="cvc"]')
            .should('be.visible')
            .type('123')
        cy.get('[data-qa="expiry-month"]')
            .type('01')
        cy.get('[data-qa="expiry-year"]')
            .type('2025')
        cy.get('[data-qa="pay-button"]')
            .should('be.visible')
            .and('be.enabled')
            .and('have.text', 'Pay and Confirm Order')
            .click()

        cy.get('[data-qa="order-placed"] > b')
            .should('be.visible')
            .and('have.text', 'Order Placed!')

        cy.downloadFile('https://automationexercise.com/download_invoice/500',
            'cypress/downloads', 'Invoice.txt')
        cy.readFile('cypress/downloads/Invoice.txt', 'base64')
            .then((base64) => {
                expect(base64).to.be.a('string')
                expect(base64).to.not.be.empty
            })
        //invoice.txt appears in cypress/downloads folder
        //a bug arises as it can process the order confirmation page of expired card too...

    })
})