name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: cypress/screenshots

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Install Trivy
        run: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg lsb-release apt-transport-https
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] \
            https://aquasecurity.github.io/trivy-repo/deb \
            $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y trivy

            - name: Run Trivy filesystem scan
              run: |
                trivy fs . \
                  --exit-code 1 \
                  --severity CRITICAL,HIGH \
                  --ignore-unfixed \
                  --format table \
                  --skip-dirs node_modules,.git